<?php

return [
    'DUBIZZLE_CALL' => 'UC_C75HXX',
    'DUBIZZLE_EMAIL' => 'UC_67115U',
    'SECONDARY_PIPELINE_ID' => 24,
    'LISTINGS_ENTITY_TYPE_ID' => 1084,
    'DEFAULT_RESPONSIBLE_PERSON_ID' => 1593, // Alyssa Ashley Erise
];
